#! /bin/sh

sxhkd &

bspc config border_width         2
bspc config window_gap          30

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc config focused_border_color \#605161
bspc monitor -d I II III IV V VI VII VIII

bspc rule -a Gimp desktop=^8 state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


hsetroot -fill ~/images/wallpaper.png
